// Copyright (C) Liang Hong (lianghong@tencent.com)

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cls.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogGroupList struct {
	LogGroupList         []*LogGroup `protobuf:"bytes,1,rep,name=logGroupList" json:"logGroupList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LogGroupList) Reset()         { *m = LogGroupList{} }
func (m *LogGroupList) String() string { return proto.CompactTextString(m) }
func (*LogGroupList) ProtoMessage()    {}
func (*LogGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc36d92deb5258cb, []int{0}
}

func (m *LogGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroupList.Unmarshal(m, b)
}
func (m *LogGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroupList.Marshal(b, m, deterministic)
}
func (m *LogGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroupList.Merge(m, src)
}
func (m *LogGroupList) XXX_Size() int {
	return xxx_messageInfo_LogGroupList.Size(m)
}
func (m *LogGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroupList proto.InternalMessageInfo

func (m *LogGroupList) GetLogGroupList() []*LogGroup {
	if m != nil {
		return m.LogGroupList
	}
	return nil
}

type LogGroup struct {
	Logs                 []*Log   `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
	ContextFlow          *string  `protobuf:"bytes,2,opt,name=contextFlow" json:"contextFlow,omitempty"`
	Filename             *string  `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	Source               *string  `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogGroup) Reset()         { *m = LogGroup{} }
func (m *LogGroup) String() string { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()    {}
func (*LogGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc36d92deb5258cb, []int{1}
}

func (m *LogGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroup.Unmarshal(m, b)
}
func (m *LogGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroup.Marshal(b, m, deterministic)
}
func (m *LogGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroup.Merge(m, src)
}
func (m *LogGroup) XXX_Size() int {
	return xxx_messageInfo_LogGroup.Size(m)
}
func (m *LogGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroup.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroup proto.InternalMessageInfo

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetContextFlow() string {
	if m != nil && m.ContextFlow != nil {
		return *m.ContextFlow
	}
	return ""
}

func (m *LogGroup) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

type Log struct {
	Time                 *int64         `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	Contents             []*Log_Content `protobuf:"bytes,2,rep,name=contents" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc36d92deb5258cb, []int{2}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*Log_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Log_Content struct {
	Key                  *string  `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log_Content) Reset()         { *m = Log_Content{} }
func (m *Log_Content) String() string { return proto.CompactTextString(m) }
func (*Log_Content) ProtoMessage()    {}
func (*Log_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc36d92deb5258cb, []int{2, 0}
}

func (m *Log_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log_Content.Unmarshal(m, b)
}
func (m *Log_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log_Content.Marshal(b, m, deterministic)
}
func (m *Log_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log_Content.Merge(m, src)
}
func (m *Log_Content) XXX_Size() int {
	return xxx_messageInfo_Log_Content.Size(m)
}
func (m *Log_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Log_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Log_Content proto.InternalMessageInfo

func (m *Log_Content) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Log_Content) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*LogGroupList)(nil), "protocol.LogGroupList")
	proto.RegisterType((*LogGroup)(nil), "protocol.LogGroup")
	proto.RegisterType((*Log)(nil), "protocol.Log")
	proto.RegisterType((*Log_Content)(nil), "protocol.Log.Content")
}

func init() { proto.RegisterFile("cls.proto", fileDescriptor_dc36d92deb5258cb) }

var fileDescriptor_dc36d92deb5258cb = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x36, 0x6a, 0x32, 0xad, 0x20, 0x83, 0xca, 0xd2, 0xd3, 0x9a, 0x53, 0x4e, 0x0b,
	0xf5, 0xe0, 0x17, 0x10, 0xea, 0x25, 0xa7, 0xfd, 0x06, 0x65, 0x59, 0x43, 0x70, 0x9b, 0x29, 0xd9,
	0x8d, 0x7f, 0x4e, 0x1e, 0xfc, 0xe2, 0xd2, 0x69, 0x52, 0x92, 0xd3, 0xcc, 0x7b, 0xbf, 0xf7, 0x86,
	0x81, 0xc2, 0xfa, 0xa0, 0x8f, 0x3d, 0x45, 0xc2, 0x9c, 0x87, 0x25, 0x5f, 0xee, 0x60, 0x5d, 0x53,
	0xf3, 0xd6, 0xd3, 0x70, 0xac, 0xdb, 0x10, 0xf1, 0x05, 0xd6, 0x7e, 0xa6, 0x65, 0xa2, 0x44, 0xb5,
	0x7a, 0x46, 0x3d, 0x15, 0xf4, 0x94, 0x36, 0x8b, 0x5c, 0xf9, 0x97, 0x40, 0x3e, 0x21, 0x7c, 0x82,
	0xcc, 0x53, 0x13, 0xc6, 0xf2, 0xed, 0xa2, 0x6c, 0x18, 0xa1, 0x82, 0x95, 0xa5, 0x2e, 0xba, 0xef,
	0xb8, 0xf3, 0xf4, 0x25, 0x53, 0x95, 0x54, 0x85, 0x99, 0x5b, 0xb8, 0x81, 0xfc, 0xbd, 0xf5, 0xae,
	0xdb, 0x1f, 0x9c, 0x14, 0x8c, 0x2f, 0x1a, 0x1f, 0xe1, 0x3a, 0xd0, 0xd0, 0x5b, 0x27, 0x33, 0x26,
	0xa3, 0x2a, 0x7f, 0x41, 0xd4, 0xd4, 0x20, 0x42, 0x16, 0xdb, 0x83, 0x93, 0x89, 0x4a, 0x2b, 0x61,
	0x78, 0xc7, 0x2d, 0xe4, 0x7c, 0xbd, 0x8b, 0x41, 0xa6, 0xfc, 0xd7, 0xc3, 0xe2, 0x2f, 0xfd, 0x7a,
	0xa6, 0xe6, 0x12, 0xdb, 0x6c, 0xe1, 0x66, 0x34, 0xf1, 0x0e, 0xc4, 0x87, 0xfb, 0xe1, 0x83, 0x85,
	0x39, 0xad, 0x78, 0x0f, 0x57, 0x9f, 0x7b, 0x3f, 0x38, 0x99, 0xb2, 0x77, 0x16, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x30, 0xfc, 0x84, 0xfc, 0x64, 0x01, 0x00, 0x00,
}
